#!/usr/bin/env bash
# Display "Best School" 10 times but for the 9th iteration display "Best Shool" and "Hi" on a new line, use while loop.

each_iteration=0

while [ $each_iteration -lt 10 ]
do
	if [ $each_iteration -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( each_iteration ))
done
