#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#   "bad luck" for the 4th iteration,
#   "good luck" for the 8th iteration,
#   "Best School" for all other iterations

each_iteration=0

while [ $each_iteration -lt 10 ]
do
	if [ $each_iteration -eq 3 ]
	then
		echo "Bad Luck"
	elif [ $each_iteration -eq 7 ]
	then
		echo "Good Luck"
	else
		echo "Best School"
	fi
	(( each_iteration++ ))
done
